<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change View_fa fa-linkedinOld</name>
   <tag></tag>
   <elementGuidId>dec7094f-1c34-4779-ad9a-088398898940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='http://www.linkedin.com/cws/share?mini=true&amp;url=http%3A%2F%2F100.100.100.199%2Femployer%2Fadvertismentpreview.jsp%3Fjc%3D0000710217%26rid%3D47%26ac%3D0000000317%26ec%3D0000000416%26index%3D']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-linkedinOld</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.linkedin.com/cws/share?mini=true&amp;url=http%3A%2F%2F100.100.100.199%2Femployer%2Fadvertismentpreview.jsp%3Fjc%3D0000710217%26rid%3D47%26ac%3D0000000317%26ec%3D0000000416%26index%3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[@class=&quot;ContentTable&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[7]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/span[@class=&quot;socialShare socialPlugin&quot;]/span[@class=&quot;socials opened&quot;]/a[@class=&quot;fa fa-linkedinOld&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://www.linkedin.com/cws/share?mini=true&amp;url=http%3A%2F%2F100.100.100.199%2Femployer%2Fadvertismentpreview.jsp%3Fjc%3D0000710217%26rid%3D47%26ac%3D0000000317%26ec%3D0000000416%26index%3D']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/a</value>
   </webElementXpaths>
</WebElementEntity>
