<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Sri LankaAfghanistanAlbaniaAlgeriaAmeric_0f8699</name>
   <tag></tag>
   <elementGuidId>b06e3c9d-66ae-437f-8c24-fd29ef8aa599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmJobSpec']/table/tbody/tr[9]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	
	
	
	
	
		
		Sri Lanka
		
		Afghanistan
		
		Albania
		
		Algeria
		
		American Samoa
		
		Andorra
		
		Angola
		
		Anguilla
		
		Antigua and Barbuda
		
		Argentina
		
		Armenia
		
		Aruba
		
		Ascension
		
		Australia
		
		Austria
		
		Azerbaijan
		
		Bahamas
		
		Bahrain
		
		Bangladesh
		
		Barbados
		
		Belarus
		
		Belgium
		
		Belize
		
		Benin
		
		Bermuda
		
		Bhutan
		
		Bolivia
		
		Bosnia and Herzegovina
		
		Botswana
		
		Brazil
		
		British Virgin Islands
		
		Brunei
		
		Bulgaria
		
		Burkina Faso
		
		Burundi
		
		Cambodia
		
		Cameroon
		
		Canada
		
		Cape Verde
		
		Cayman Islands
		
		Central African Republic
		
		Chad
		
		Chile
		
		China
		
		Colombia
		
		Comoros
		
		Republic of the Congo
		
		Cook Islands
		
		Costa Rica
		
		Croatia
		
		Cuba
		
		Curacao
		
		Cyprus
		
		Czech Republic
		
		Democratic Republic of Congo
		
		Denmark
		
		Diego Garcia
		
		Djibouti
		
		Dominica
		
		Dominican Republic
		
		East Timor
		
		Ecuador
		
		Egypt
		
		El Salvador
		
		Equatorial Guinea
		
		Eritrea
		
		Estonia
		
		Ethiopia
		
		Falkland (Malvinas) Islands
		
		Faroe Islands
		
		Fiji
		
		Finland
		
		France
		
		French Guiana
		
		French Polynesia
		
		Gabon
		
		Gambia
		
		Georgia
		
		Germany
		
		Ghana
		
		Gibraltar
		
		Greece
		
		Greenland
		
		Grenada
		
		Guadeloupe
		
		Guam
		
		Guatemala
		
		Guinea
		
		Guinea-Bissau
		
		Guyana
		
		Haiti
		
		Honduras
		
		Hong Kong
		
		Hungary
		
		Iceland
		
		India
		
		Indonesia
		
		Iran
		
		Iraq
		
		Ireland
		
		Israel
		
		Italy
		
		Ivory Coast
		
		Jamaica
		
		Japan
		
		Jordan
		
		Kazakhstan
		
		Kenya
		
		Kiribati
		
		Kuwait
		
		Kyrgyzstan
		
		Laos
		
		Latvia
		
		Lebanon
		
		Lesotho
		
		Liberia
		
		Libya
		
		Liechtenstein
		
		Lithuania
		
		Luxembourg
		
		Macau
		
		Macedonia
		
		Madagascar
		
		Malawi
		
		Malaysia
		
		Maldives
		
		Mali
		
		Malta
		
		Marshall Islands
		
		Martinique
		
		Mauritania
		
		Mauritius
		
		Mayotte
		
		Mexico
		
		Micronesia
		
		Moldova
		
		Monaco
		
		Mongolia
		
		Montenegro
		
		Montserrat
		
		Morocco
		
		Mozambique
		
		Myanmar
		
		Namibia
		
		Nauru
		
		Nepal
		
		Netherlands
		
		Netherlands Antilles
		
		New Caledonia
		
		New Zealand
		
		Nicaragua
		
		Niger
		
		Nigeria
		
		Niue
		
		Norfolk Island
		
		North Korea
		
		Northern Marianas
		
		Norway
		
		Oman
		
		Pakistan
		
		Palau
		
		Palestine
		
		Panama
		
		Papua New Guinea
		
		Paraguay
		
		Peru
		
		Philippines
		
		Poland
		
		Portugal
		
		Puerto Rico
		
		Qatar
		
		Reunion
		
		Romania
		
		Russian Federation
		
		Rwanda
		
		Saint Helena
		
		Saint Kitts and Nevis
		
		Saint Lucia
		
		Saint Barthelemy
		
		Saint Martin (French part)
		
		Saint Pierre and Miquelon
		
		Saint Vincent and the Grenadines
		
		Samoa
		
		San Marino
		
		Sao Tome and Principe
		
		Saudi Arabia
		
		Senegal
		
		Serbia
		
		Seychelles
		
		Sierra Leone
		
		Singapore
		
		Sint Maarten
		
		Slovakia
		
		Slovenia
		
		Solomon Islands
		
		Somalia
		
		South Africa
		
		South Korea
		
		South Sudan
		
		Spain
		
		Sudan
		
		Suriname
		
		Swaziland
		
		Sweden
		
		Switzerland
		
		Syria
		
		Taiwan
		
		Tajikistan
		
		Tanzania
		
		Thailand
		
		Togo
		
		Tokelau
		
		Tonga
		
		Trinidad and Tobago
		
		Tunisia
		
		Turkey
		
		Turkmenistan
		
		Turks and Caicos Islands
		
		Tuvalu
		
		Uganda
		
		Ukraine
		
		United Arab Emirates
		
		United Kingdom
		
		United States of America
		
		U.S. Virgin Islands
		
		Uruguay
		
		Uzbekistan
		
		Vanuatu
		
		Vatican City
		
		Venezuela
		
		Vietnam
		
		Wallis and Futuna
		
		Yemen
		
		Zambia
		
		Zimbabwe
		
		DEFAULT
		
	 
	
	 
	
		 Acharigama (Nawagattegama)Acharigama (Thalawa)AchchamulaiAchchuveliAdampan (Karachchi)Adampan (Manthai West)AdampanaiAdappanvilluAdawikandaAddalachenaAgalawattaAgaliyaAgarapatanaAgbopuraAhangamaAhungallaAiyamperumalAkaranadiyaAkattikkulamAkattimurippuAkirikandaAkkaraipattuAkmeemana (AkmeemanaAkmeemana (Imaduwa)AkurambodaAkuranaAkuressaAkurugodaAlagalla (Mawanella)Alagalla (Vavuniya South)AlagollewaAlakolawewaAlaluwaAlampilAlankerniAlankudaAlankulamAlapaladeniyaAlawatugoda (Akurana)Alawatugoda (Welimada)Alawwa (Alawwa)Alawwa (Warakapola)AlayadiwembuAlgamaAliavalaiAlipalaiAlkaddiveliAllaippiddiAlubogollaAlubomullaAlupolaAlupota (Badalkumbura)Alupota (Pelmadulla)Alut HammillewaAlut OyaAlutgama (Beruwala)Alutgama (Kotawehera)AluttaramaAlutwalaAlutwewaAluvihareAlvaiAlwakumburaAmarakongamaAmbagahawewa (Beruwala)Ambagahawewa (Nochchiyagama)Ambagamuwa (Ambagamuwa)Ambagamuwa (Yatinuwara)AmbagasdowaAmbagaswewa (Hingurakgoda)Ambagaswewa (Horowpothana)Ambagaswewa (Medirigiriya)AmbalakandaAmbalamAmbalangodaAmbalantotaAmbaleAmbamallaAmbanaAmbanganga KoralayaAmbanpolaAmbanporuwaAmbataleAmbepitiyaAmbepussaAmbetennaAmbewelaAmbulgamaAmitirigalaAmpakamamAmpanAmparaAmpegamaAmugodaAmunekanduraAmunukole (Galgamuwa)Amunukole (Nochchiyagama)AnalaitivuAnamaduwaAnangkaniAnaolondewaAndallaAndankaniAndankulam (Manthai West)Andankulam (Maritimepattu)AndiambalamaAndiawelaAndigama (Anamaduwa)Andigama (Mahakumbukkadawala)AndiyagalaAndiyapuliyankulamAngamedillaAngodaAngulanaAngulugahaAngunakolapelassa (Angunukolapelessa)Angunakolapelessa (Thanamalwila)AnguruwatotaAnguruwellaAnkumburaAnnaiwilundawaAnnatevanmaduAntanantidalAnukkangalaAppakkuttikinattadiArabbodaArabokkaArachchikattuwaAralaganwilaAraliAranayakaArangalaArassadichchenaiArawaArawattaArialaiArippuArtiadimunaiAruakaluArukuveliArukwattaAsikulamAsirikgamaAtabageAtale (Badalkumbura)Atale (Palindanuwara)AthuraliyaAttanagallaAttaragallewaAttikulamaAttimoddaiAturaAturugiriyaAtuwagallaAtweltotaAukanaAvaddaveliAviladiAvissawellaAyagamaAyiliAyittiyamalaiAyiyatigewewaBadalgamaBadalkumburaBaddegamaBadullaBaduluwelaBadureliyaBakinigahawelaBakkiellaBakmetotaBakmiwewaBakunawalaBalagollagamaBalallaBalanaBalangodaBalapitiyaBallakatuwaBalukekulakadaBambalapitiyaBambarabeddaBambarabotuwaBambaragahawattaBamunakotuwaBamunugama (Mulatiyana)Bamunugama (Polpithigama)BAnagalaBandara KumbukwewaBandara UlpotaBandaradeniyaBandaragamaBandarawelaBandirippuwaBanduragodaBangadeniyaBaragedaraBarandaraBarigodaBaselineBatagamaBatapolaBatayayaBatewelaBathmedillaBattulu OyaBatumullaBatuwattaBeddegamaBeddewalaBedigamaBedigantotaBeliankadawalaBeliattaBeligallaBelihul OyaBeliyakandaBellannewalaBellapitiyaBeminiyanwilaBemmullaBengamuwaBentotaBeragalaBeragamaBeralapanataraBeruwalaBeruwewaBibilaBibilegamaBihalpolaBindunawewaBingiriyaBingodaBintennaBisokotuwaBiyagamaBodagamaBogahapelessaBogahawewa (Nochchiyagama)Bogahawewa (Palagala)BogawantalawaBogomuwaBohityaBokkebeddaBolawattaBoossaBopagodaBopeBope (Poddala)BoraessaBoragasketiyaBorakandaBoralaBoralanda (Ella)Boralanda (Welimada)BoralesgamuwaBoralugodaBorupanwewaBotalawaBotaleBotategamaBrooksideBuddamaBujjamuwaBulanewewaBulankulamaBulatgamaBulathkohupitiyaBulathsinhalaBulnewaBulugahagodaBulugahalandaBulupitiyaBundalaButkandaButtalaCarolinaChadayantalawaChalaiChamalankulamChankanaiChantiaruChavakachcheriChavalkudaiCheddikulamCheddipalayamCheddiyakurichchiChemmalaiChempankunduChempiyanpattuChenakuddiruppuChenkaladiChilavattaiChilawChina BayChinnakkunchukulamChinnavalayankadduChirunavatkulamChittandikudiChulipuramChundankaduChundikkulamChunnakamChunnavilColombage AraColomboColombo 1Colombo 10Colombo 11Colombo 12Colombo 13Colombo 14Colombo 15Colombo 2Colombo 3Colombo 4Colombo 5Colombo 6Colombo 7Colombo 8Colombo 9Cotta RoadDabarellaDachchidamanaDaladagamaDalukgollaDamanaDambadeniya (Madulla)Dambadeniya (Narammala)DambagahawelaDambagallaDambagolla (Kandaketiya)Dambagolla (Naula)DambalawinnaDambanaDambokkaDambullaDamegamaDamiangodaDammanatennaDamminnewelaDampandurawaDandagamuwaDandubendiruppaDangaswewaDanigalaDankandaDankoluwaDankotuwaDanowitaDaraluwa (Gampaha)Daraluwa (Pannala)DastotaDaulagalaDebarawewaDebokkawaDedduwawalDediyagalaDedugalaDeegalaDegalarambaDehenakandaDehiattakandiyaDehigahawelaDehigamaDehiovitaDehiwalaDekatanaDelaDelftDelgodaDellabodaDelmellaDeloluwaDelthotaDelwalaDematagollaDematawewaDemodaraDemunnewaDenagama (Hakmana)Denagama (Imbulpe)DenipitiyaDeniyayaDenuwakandaDerangalaDeraniyagalaDevinuwaraDewahandiyaDewalapolaDewalegamaDewanagalaDewaradapolaDewaturaDeyiyandaraDeyiyannewelaDharga TownDickwellaDiddeniya (Ibbagamuwa)Diddeniya (Poojapitiya)DiganaDiganpathahaDigitowaDijjulanaDikheraDikkapitiyaDikkumburaDikoyaDikwella (Dickwella)Dikwella (Hali Ela)DikwewaDimbulaDimbulagalaDimbulanaDivulapitiyaDivullegamaDiwulana (Manmunai South - West)Diwulana (Thamankaduwa)DiwulankadawalaDiwulapitiyaDiwullewaDiwulwewa (Galenbidunuwawe)Diwulwewa (Thirappane)DiyabetmeDiyabubulaDiyagama (Homagama)Diyagama (Kaluthara)Diyagama (Nikaweratiya)Diyagama (Nuwara Eliya)DiyainnaDiyalumaDiyatalawaDiyatittawewaDiyatureDodampapitiyaDodampeDodanduwaDodangaslandaDodangodaDolagalwelaDolekandaDolosbageDoloswalaDoluwaDombagahawela (Lahugala)Dombagahawela (Siyambalanduwa)DombawalaDombemedaDompeDondraDoraliyaddaDumbuluwaDummalasuriyaDummalatennaDunagahaDunekedeniyaDunumadalewaDunupotagamaDunuwattegamaDunuwila (Medadumbara)Dunuwila (Wilgamuwa)Dutuwewa (Horowpothana)EachchilampattaiEbatuwaEgallaEgaloyaEgoda UyanaEgodayagamaEheliyagodaEhetuwewa (Ehetuwewa)Ehetuwewa (Nuwaragam Palatha Central)EkalaEkiriyaEkiriyankumburaEkkassaEkneligodaEladuwaElagamuwaElagomuwa (Naula)Elagomuwa (Polpithigama)ElaheraElallaElapathaElapatwewaElayappattuwaElephant PassElewelaEliwilaElkaduwaElkanduraEllaEllakondaEllawalaEllegodaEllepolaEllewelaElpitiyaEluthumadduvalEluwapolaEmbilipitiya (Embilipitiya)Embilipitiya (Madulla)EmbogamaEmbuldenlyaEndanaEnderamullaEpaladeniyaEppawala (Palugaswewa)Eppawala (Thalawa)EragamaEramaduEramullaEravurEravur PattuEravur TownErepolaEriyagamaEriyawaErukkilampiddiErumativu (Kalpitiya)Erumativu (Poonakary)EtakadaEtalaiEtambagaskadaEtanwelaEtiliwewaEtimoleEtorahenaEttempitiyaEwariyapelessaFortFoul PointGal OyaGalabeddeGaladeniyaGalagedaraGalahaGalahitiyawaGalapitagalaGalapitamadaGalauda (Hanguranketha)Galauda (Kandaketiya)GalawewaGalboda (Naula)Galboda (Pasbage Korale)GalbokayaGalbokka (Rideemaliyadda)Galbokka (Wellawaya)GalellegamaGalenbidunuwaweGalewelaGalewewaGalgamuwa (Galgamuwa)Galgamuwa (Madulla)Galgamuwa (Maspotha)GalgedawalaGalgomuwaGalhetiyaGaligamuwa (Galigamuwa)Galigamuwa (Rideemaliyadda)Galkadawala (Ehetuwewa)Galkadawala (Nuwaragam Palatha Central)GalkaduwaGalketigedaraGalkiriyagamaGalktuwaGalkulama (Anamaduwa)Galkulama (Nawagattegama)Galkulama (Thirappane)Gallala GalleGalle Four GravetsGallella (Rathnapura)Gallella (Thamankaduwa)GallenaGallewaGallindaGallodaiGalmedaGalnewaGaloya JunctionGalpaya (Ganga Ihala Korale)Galpaya (Weligepola)GaltumbeGalwangedipotaGalwelawattaGamagodaGamakandaGamayagamaGambirigaswewaGamekumburaGamewelaGammaduwaGampaha (Gampaha)Gampaha (Haldummulla)GampolaGanangollaGandaraGanegama (Baddegama)Ganegama (Pelmadulla)Ganegoda (Elpitiya)Ganegoda (Mirigama)GanekandaGanemullaGanewalpolaGanewattaGanga Ihala KoraleGangawata KoraleGangodagamaGantalawaGassandalupotaGedigaswelanaGeli OyaGendagalaGetahettaGetamannaGetangamaGewilipitiyaGilimaleGinigathenaGinnoruwaGintotaGiragamaGirandurukotteGiratalanaGiribawaGiritaleGiriullaGnanikulamaGodagama (Homagama)Godagama (Ibbagamuwa)GodagedaraGodakawelaGodakoggallaGodapolaGodawelipokuna HelaGodigomuwaGojaragamaGokarellaGomarankadawalaGonadeniya (Rideegama)Gonadeniya (Weeraketiya)GonaduwaGonagalaGonagaldeniyaGonagamaGonamotawaGonapinuwalaGonapolaGonarambaGonawela (Bibila)Gonawela (Dambulla)GonoruwaGopelessaGowinnaGulanawattaGurubabilaGurudeniyaGurugallaGurugodaGuruhelaGurukumburaGurulepolaGurulubeddaGuruluwanaGurutalawaGuruwelaHabaraduwaHabarakadaHabaranaHabarewaHabessaaHaburugalaHakgalaHakmanaHaldummullaHalgollaHali ElaHali GalkadawalaHalmillagaswewaHalmillaketiyaHalmillawewaHalmillewaHalpanwilaHalpe (Imbulpe)Halpe (Thihagoda)HalwaturaHamakandupitiyaHambantotaHambegamuwaHammillawetiyaHammillewa (Kahatagasdigiliya) Hammillewa (Nochchiyagama)Hammillewa (Palagala)Hammillewa (Palugaswewa)Hammillewa (Thalawa)HandaganawaHandagiriyaHandapangodaHandapanwelaHangaran OyaHangiliellaHanguranketaHanwella (Hanwella)Hanwella (Udadumbara)HapporuwaHapukandaHaputhaleHarankahawaHarasbeddaHarispattuwaHasalakaHatagalaHatamune (Devinuwara)Hatamune (Hingurakgoda)HatangalaHataraliyaddaHatkeleHattonHavannawelaHedeniyaHedidenikandaHeendeniyaHelambeHelambewa (Galnewa)Helambewa (Maha Vilachchiya)HelaweHembarawaHemmatagamaHendalaHendiyapolaHenegama (Akuressa)Henegama (Balangoda)Henegama (Mahara)HepolaHeraliwattaHeratgamaHerath HammillewaHettigamaHettipolaHettuwewaHewahetaHewanewelaHeyiyagamaHidagamawattaHidiyamullaHigurakgalaHikkaduwaHikkagalaHimbiliyakadaHindagalaHindakaramullaHingulaHinguraHingurakgodaHingurukaduwaHinidumaHiralouvahHiralugamaHiranaHirigalkatuwaHiripitiya (Ganewatta)Hiripitiya (Siyambalanduwa)HiripitiyagamaHiriyalaHiriyalegamaHittetiyaHomagamaHorabokkaHoradoruwaHorahinellaHoranaHorangallaHorapeHorapolaHoratepolaHoriwila (Dimbulagala)Horiwila (Palugaswewa)HorombuwagamaHorowpothanaHoruwilaHowpeHulandawa (Moneragala)Hulandawa (Pitabeddara)HulannarakadaHulanugeHungamaHunnasgiriyaHunugallewaHunupitiyaHunupolaHunupolayagamaHunuvilagamaHuratgamuwaHurikaduwaIbbagamuwaIchchantivuIchchilampattaiIdaikkaduIdaikkuruchchiIdalgashinnaIdambowaIdangodaIddagodaIhala PuliyankulamaIhalagalgamaIhalagama (Kekirawa)Ihalagama (Mihintale)Ihalagama (Nikaweratiya)IhalakolaeliyaIiuktennaIkirigollewaIkiriwewaIlakkantaiIlamarutankulamIlankaituralIlantaikkulamIlavalaiIlluktennaIlluppaiyadichchenaiIlukhenaIlukwewaIluppaikkadavaiIluppukulamaImaduwa (Imaduwa)Imaduwa (Welipitiya)ImbulgodaImbulpeImburpitiyaInamalawaIndigollewaIndiwewaInduruwa (Bentota)Induruwa (Rathnapura)InginiyagalaIngiriyaInuvilIpalogamaIpologamaIrakkamamIrakkandiIralakkulamIramiyankulamIrampaikkulam (Medawachchiya) Irampaikkulam (Vavuniya)Iranai IluppaikkulamIranaitivu NorthIranaitivu SouthIranamaduIratperiyakulamaIriyagollaIriyatotaItalwetunuwewaItalwiddawewaIttapanaIttekandaIttikulam (Nochchiyagama)Ittikulam (Vavuniya South)IyakachchiJa_ElaJaffnaJanduraJayanthipuraJulampitiyaKachchigalaKachchilamaduKadahapolaKadawata (Biyagama)Kadawata (Kebithigollewa)KadawatgamaKaddaikaduKaddaiparichchanKadduwaKadigamuwaKadigawaKadigomuwaKadugannawaKadurugalwattaKadurugasdamanaKadurupitiyaKaduruwelaKaduwela (Kaduwela)Kaduwela (Mahawa) KahaduwaKahagalaKahallaKahandamodaraKahangamaKahapatwilaKahatagahaKahatagasdigiliyaKahatapitiya (Horana)Kahatapitiya (Lunugala)KahatuduwaKahawaKahawalaKahawaththaKahawatta (Elapatha)Kahawatta (Madampe)Kahawatta (Pelmadulla)Kaikawala (Rattota)Kaikawala (Udadumbara)KainaddinakulamKaitadiKakkapalliyaKakkativuKakupandiyawaKala OyaKala WewaKalagahaullaKalagedihenaKalankuttiyaKalapoomyKalawanaKalawelgalaKalawilaKalayanuruwaKaleliyaKalkudah (Koralai Pattu (Valach.))Kalkudah (Manmunai West)Kalladi (Manmunai North)Kalladi (Puttalam)KallanchiyaKallarKallarwaKallikaiKallikkulamKalmunai (Kalmunai)Kalmunai (Poonakary)KalogahawelaKalpeKalpitiyaKaluachchigamaKaluaggalaKalubowitiyanaKaluebeKalugamuwaKalugangaKalukunnanmmaduwaKalundewaKalupahana (Agalawatta)Kalupahana (Haldummulla)Kalupahana (Ingiriya)KalupeKalutaraKalutavalaiKalutharaKaluvanchikudiyiruppuKaluwilaKambakkoddaiKambarawaKamburugamuwaKamburupitiyaKanakarayankulamKanalkumburaKanamulaiKanankeKananwilaKanchurankudahKandakaduKandaketiyaKandakkudaKandakuliKandalamaKandalveliKandanaKandanketiyaKandanuwaraKandapolaKandavalaiKandeKandegedaraKandegodaKandepitawelaKandyKankaniyamullaKankesanturaiKankuveliKannaddi (Manthai West)Kannaddi (Vengalacheddiculam)KannankudahKannimaduwaKanniyaiKantaleKanthaudaiyarpuvarsankulaKanulwelaKapalturaiKapiriggamaKappachchiKappaladiKapugodaKapugollewaKapurellaKapuruwediwelaKarachchiKaradikkulamaKaradikkuliKaradipuvalKaradiyanaruKaragahatennaKaragahawelaKaragodaKarainagarKaraitivuKaraiyamullivaikalKarakojagahatennaKarambe (Mahawa)Karambe (Mundalama)KarambewaKarametiyaKarampaimaduKarampanKaranavaiKarandegamaKarandeniyaKarandhaiKarappukkuttiKarativuKaraveddiKaraveddiyaruKaraveddyKarawanellaKarawilaKarawitaKarikattaiKarisalKariyalivayalKarunchamunaiKarunkalikkulamKaruppaddamurippuKaruvaddukkeniKaruwalagaswewaKaruwalakudaKataboweKatadoraKatagamuwaKatana (Divulapitiya)Katana (Katana)KatanwilaKataragamaKathiraveliKathurupitiyaKatkidankuKatkovalamKatkulamKattaikaduKattakaduwaKattamurichchanaKattankudiKattarasinnakulamKattimahanaKattuwaKatu PuliyankulamKatudampeKatugahagalgeKatugahahenaKatugastotaKatukeliyawa (Hingurakgoda)Katukeliyawa (Kahatagasdigiliya)KatukellyawaKatukurundaKatumanaKatunayakaKatuneriyaKatupanaKatupathwelaKatupatwewa PahalaKatupitigamaKatupitiyaKatupotha (Katupotha)Katupotha (Kuliyapitiya East)KatuwanaKatuwanwilaKaudottawaKavllanvaddathalvuKavutarimunaiKawarakkulamaKawudupelellaKayinattamaKayirakgamaKaytsKebithigollewaKeembiyaKeenawelaKeerimalaiKegallaKehelellaKehelkumburaKehelullaKehelwalaKehelwatta (Aranayaka)Kehelwatta (Buttala)KekanaduraKekirawaKekiribodaKekirrihenaKekulakadaKekulawelaKelaniyaKele KarambewaKelegamaKelewaKeligamaKeliyawalanaKempaneKendaketiyaKendewa (Ehetuwewa)Kendewa (Rambewa)KeppapulavuKeppetipolaKeppitiwalanaKesbewaKetakeleKetawala (Hali Ela)Ketawala (Pasgoda)KibissaKidachchuriKilaliKilanguppalaiKiliveddiKimbulapitiyaKinanaKindelpitiyaKindigodaKinniya  (Town &amp; Gravets)Kinniya (Kinniya)KiragalaKiralogamaKiramaKiranaulpotaKiranchiKiribaddana HelaKiribbewaKiriellaKirigollewaKirimetitennaKirimetiyagamaKirimetiyawa (Katupotha)Kirimetiyawa (Medawachchiya)KirimundalKirinda (Kirinda Puhulwella)Kirinda (Tissamaharama)Kirinda PuhulwellaKirindegamaKirindiwelaKiriwalaKiriwelgodaKiriyagaswewaKiriyankalliKitulgalaKitulgalwilaKitulkoteKituluttuwaKiulewadiyaKivulaKivulagamaKiwulekada (Gomarankadawela)Kiwulekada (Nuwaragam Palatha Central)KobeiganeKochchikadeKodaikallarKodalikkalluKodayannaKoddamunaiKodikamamKodinarawaKoggalaKoggallaKohalanwelaKohilapokunaKoholanaKoholankalaKohombagaswewaKohombanaKohombeKokavil newKokavil oldKokkadichcholaiKokkavilleKokkawila (Chilaw)Kokkawila (Kalawana)KokkuttoduvaiKokkuveliyaKokkuvilKokmaduwaKoknaharaKolakanaweliKolamantalawaKolavilKolawayaKolayayeKollankulamaKollarsirukkulamKollupitiyaKolongallaKolonnaKolonnawaKomariKomariyaKompanachchiKomputukkiKompuvaittakulamKondaichchiKondavattavanKondavilKonduruwawaKongahamankadaKongahawelaKongollewaKonketiyaKonkumbukgollewaKonwewa (Kahatagasdigiliya)Konwewa (Mahawa)KopayKoraikalliamadduKorakkankadduKoralai P. W. (Oddamavadi)Koralai Pattu (Valach.)Koralai Pattu NorthKoralawellaKorasagallaKorossaKorukkapuliyuttuKoruppugamaKosawakulamKosgama (Haldummulla)Kosgama (Hanwella)Kosgama (Panwila)KosgodaKoshenaKoslandaKossapolaKossowaKoswattaKotadeniyawaKotagalaKotagamaKotagodaKotakumbukkaKotapolaKotavilaKotaweheraKotawellaKothmaleKotiagodaKotiyagalaKotiyagallaKotmaleKottagalaKottagodaKottapitiyaKottawa (Maharagama)Kottawa (Yakkalamulla)KotteKottimbulwalaKottukachchiyaKotugodaKotuwewaKovilporativuKoviltirimaduKovitkulamKoyitkulamKoyitkunchukkulamKuaunduwinnaKuchchaveliKuda OyaKudagalkadegamaKudagama (Medawachchiya)Kudagama (Thalawa)KudahakapolaKudakatnoruwaKudaligamaKudapanaKudarappuKudattanaiKudavilaKudawaKudawewa (Anamaduwa)Kudawewa (Giribawa)Kudawewa (Mahawewa)Kudawewa (Mihintale)Kudawewa (Rambewa)Kudramalai PointKudugalgodellaKuduweKuduwilaKukulkatuwaKukuranpolaKulairetamKulamurippuKuliyapitiyaKuliyapitiya EastKuliyapitiya WestKulumiwakadaKumadiyaKumanaKumbaladeniyaKumbalgama (Imbulpe)Kumbalgama (Mawanella)KumbalgamuwaKumbukeKumbukgeteKumbukgollaKumbukkadawalaKumbukkanaKumbukwewa (Ibbagamuwa)Kumbukwewa (Karuwalagaswewa)Kumbukwewa (Kotawehera)Kumbukwewa (Nikaweratiya)Kumbukwewa (Palugaswewa)Kumbukwewa (Sooriyawewa)KumbunumulaiKummakulamKummanaruKumpurupiddiKumulamunai (Maritimepattu)Kumulamunai (Poonakary)Kunchikulama (Ipalogama)Kunchikulama (Thirappane)KunchukkulamKundasaleKunthavediKuranaKuratiyawaKurichuddakulamKurisuddamaduKurugamaKurukeppetiyawaKurukkalkulamKurukkalmadamKurumunveliKuruncamunaiKurundanaKurundugahahetekmaKurunegalaKurunthankulamKurupitaKuruwitaKuruwitennaKuttapitiyaLabuduwaLabugamaLabunoruwaLabuyayaLaggala (Laggala-Pallegama)Laggala-Pallegama (Laggala-Pallegama)LahugalaLandajulanaLandawattaLandegamaLankapuraLatpanduraLaxapanagallaLeangawellaLellopitiyaLenadoraLenewaLihiriyagamaLikolapitiyaLindagalaLindawewaLindulaLiyangollaLunawaLunugalaLunugallaLunugamveheraLunuwilaMabingodaMabotuwanaMadahapolaMadahinnaMadakumburaMadalassaMadametotaMadampagamaMadampeMadampellaMadapataMadapokunaMadatugamaMadawachchiMadawachchiyaMadawala (Matale)Madawala (Palugaswewa)MadawallandaMadduvilMadduvilinduMadgepolaMadhu (Madhu)Madhu (Vavuniya)MadipolaMadittegamaMadola (Bulathsinhala)Madola (Opanayaka)MadugodaMadukandaMadulkeleMadulla (Madulla)Madulla (Walapane)MadulsimaMadumanaMadurankuliMadurawalaMaduru OyaMadurupitigamaMaduwanwalaMaeliyaMagalaMagalegodaMagamaMagedaraMaggonaMaha IluppallamaMaha InduruwaMaha KanumullaMaha KirindaMaha KongaskadaMaha NanneriyaMaha OyaMaha TorawaMaha VilachchiyaMahabage (Wattala)Mahabage (Yatiyanthota)MahabolanaMahaella (Dehiattakandiya)Mahaella (Eravur Pattu)MahagalkadawalaMahagamaMahagangodaMahaiyawaMahakachchakodiyaMahakalugollaMahakarambewaMahakeliyaMahakumbukkadawalaMahamullegamaMahaoyaMahapallegamaMahara (Biyagama)Mahara (Mahara)MaharachchimullaMaharagamaMahaulpotaMahauswewaMahawaMahawalaMahawalatennaMahawanawelaMahawelaMahawelatotaMahawerabendiyawaMahawewaMahawllachchiyaMahilvaddavanMahirawaMahiyanganayaMahoMakandura (Mulatiyana)Makandura (Pannala)MakewitaMakiladitivuMakolaMakulgaswewaMakulpotaMakumburaMaladanambeMalaganeMalaimuntalMalamiriyagamaMalavarayankaddaiadampanMaldeniya (Dehiovita)Maldeniya (Kothmale)MalibodaMaliduwaMalikaiMalimbadaMalittaMalivadiMaliyagamaMalkampiddyMallakamMallawapitiyaMalmikandaMalwalaMalwanaMalwattaiMamadalaMamaduwaMaminiyawaMammiangaMampuriMamulaiMamunugamaManagamaManahindaManalkaduManalkulam (Nanaddan)Manalkulam (Tunukkai)ManamperigamaManativuManawelaMandaitivuMandaran NuwaraMandula OyaMandurManelkuduManeruwaManewaMangalaweliManipayManiyarakulamMankaduMankanaiMankeniMankulam (Oddusuddan)Mankulam (Vengalacheddiculam)ManmunaManmunai NorthManmunai P. (Araipattai)Manmunai S. and EruvilpattuManmunai South - WestManmunai WestMannampitiyaMannar TownMannawattaManning TownManniyakulamMantaiManthai WestMapalanaMapitigamaMaradankadawala (Giribawa)Maradankadawala (Kekirawa)MaradanmaduwaMaradolaMaragawewaMarailuppaiMaraiyadittakulamMarakandaMarakolliyaMarangallawahawaMarassapaMaratennaMaravanpulavuMarawilaMariarawaMarichchukkaddiMaritimepattuMarutadikulamMarutankulamMaruthnkernyMarutodaiMaskeliyaMaspannaMaspothaMataleMataraMatara Four GravetsMathai EastMathugamaMatiyamaduMattakaMatugamaMaturataMausakelleMavadimunmariMAveliturai JettyMawalgahaMawananaMawanellaMawaralaMawathagama (Mawathagama)Mawathagama (Rasnayakapura))Mawila (Nattandiya)Mawila (Welikanda)MayilagaswewaMayilewaMedadumbaraMeda-ElaMedagama (Galgamuwa)Medagama (Medagama)MedagangodaMedapihillaMedaulpotaMedawachchiyaMedawalaMedawela (Imbulpe)Medawela (Passara)MedelpolaMedirigiriyaMeditaleMediyawa (Ambanpola)Mediyawa (Morawewa)Mediyawa (Thalawa)Meegaha BeraliyaMeegahakivulaMeesalaiMegaswewaMekichchawaMenikdiwelaMerawalaMetigahatennaMetikewaMetiyaganeMeyankollaMiddeniyaMidelladeniyaMidigamaMiellaMigahadigiliyaMigahajanduraMigahakivulaMigahatennaMigahawattaMigahawela (Buttala)Migahawela (Ganewatta)Migahawela (Nattandiya)MigalewaMigamaMigasaraMigaswewaMigodaMihintaleMillaniyaMillawanaMilleniyaMillewaMimureMinipeMinipogodaMinneriyaMinuwangodaMipagamaMipe JunctionMirahalaMirahawatteMirigamaMirihenegamaMirijjawalaMirisgoni Oya JunctionMirissaMiriswatupalataMirusuvilMitirigalaMitiyagodaMiyallawaModarawanaMolamureMolewaMolligodaMonaragalaMoolaiMoragahamadaMoragahapitiyaMoragahawewa (Kobeigane)Moragahawewa (Nawagattegama)MoragalaMoraganeMoragoda (Kekirawa)Moragoda (Kolonna)Moragolla (Galewela)Moragolla (Kotawehera)MoragollagamaMorahelaMorakandaMorakewaMoramalpokunaMorapeMoratuwaMorawaka (Kebithigollewa)Morawaka (Kotapola)Morawewa (Horowpothana)Morawewa (Morawewa)MotagalaMotakepupatanaMotuwaramMt. LaviniaMudalakkuliyaMudawaMudduchchenaiMudiyannegamaMudukaduMudunpitaMuduwelipokunaMukamalaiMukkuwa ToduwaMulakandaveliMulanaMulatiyanaMulendiyawalaMulgamaMulhalkelleMulkirigalaMullaittivuMullegamaMullikkulamMullipothanaMullitidalMulliyanMulliyavalaiMunagamaMunaikkaduMunamaldeniyaMundalamaMundampiddiMundelMundumurippuMunthanaMurandanveliMurasumoddaiMurikandiMurukkuwatawanaMurungahitikandaMurunkanMurutalawaMurutewelaMuruttettukandaMusalaiMusalkuttiMusalpittiMutaliyarkulam (Oddusuddan)Mutaliyarkulam (Vengalacheddiculam)MuthiyanganeMuttettutennaMutturMutugalaMutugallaMuturNabadawewaNachchadoowa (Nachchadoowa)Nachchadoowa (Nuwaragam Palatha East)NachchikkudaNachivantivuNaddankandalNadiganwelaNadukkudaNagadaranewaNagamaduNagoda (Dodangoda)Nagoda (Nagoda)NagollagamaNaipaddimunaiNaiwalaNakarkoyilNakattaivuNakiyadeniyaNakkalaNakulugamuwaNalandaNalapayaNallachchiyaNallamudewaNallatannitoduvayNallur (Nallur)Nallur (Poonakary)Nalugas AraNamal OyaNambannaNamunukulaNanaddanNannapurawaNanu OyaNaotunnaNapawalaNaragalaNarahenpitaNarakkaliNarammalaNarangoda (Galigamuwa)Narangoda (Pannala)NarangomuwaNaranpanawaNarantanaiNarawilaNarthupanaNattandiyaNaulaNavadantaivuNavatkadu (Chavakachcheri)Navatkadu (Kalpitiya)NavatkudahNavatkuliNavinnaNavithanveliNawadagalaNawagamuwaNawagattegamaNawaladiNawalapitiyaNawanaNawandankulamNawelaNayakomburaNayinamaduNeboda (Dodangoda)Neboda (Thanamalwila)Nedunkeni (Mathai East)Nedunkeni (Vavuniya North)NeethaiNegamaNegampahaNegomboNekatiwaduressaNelliadiNelliyaNelluwaNelubewaNelukkulamNelundeniyaNelunpitiyaNeluwa (Hali Ela)Neluwa (Neluwa)NeriyakulamNevugalaNikaweheraNikaweratiyaNikawewa (Giribawa)Nikawewa (Karuwalagaswewa)Nikawewa (Maha Vilachchiya)Nikawewa (Medirigiriya)Nikawewa (Polpithigama)Nikawewa (Thanamalwila)NilaveliNilawabeddaNilawalaNildandahinnaNilgalaNilobeNinthavurNiriellaNirveliNitogamaNittambuwaNitulgollewaNivithigalaNiyadurupolaNiyagamaNiyandawaneNochchikkulam (Madhu)Nochchikkulam (Maha Vilachchiya)Nochchikkulam (Vavuniya North)NochchiyaNochchiyagamaNoongahakiulaNorton BridgeNorwoodNugadandaNugawelaNugegodaNunavilNuraicholaiNuwara EliyaNuwaragam Palatha CentralNuwaragam Palatha EastNuwarawewaObbekotaOddankulamOddumaduOddusuddanOdduveliOggomuwaOhiyaOkandaOkewelaOkkarnpitiyaOlaittoduwaiOlugaskadaOlukarandaOlukkuliyaOlumaduOluvilOmantaiOmattaOmunaOnegamaOpalgalaOpanayakaOpata (Godakawela)Opata (Thawalama)OttapanaiOttappuwaOyamaduwaPachchanurPachchilaipalliPadagodaPadavi Sri PuraPadaviyaPadavkemaPadawalaPadawiyaPaddawalaPaddikkudiyiruppuPaddippalaiPaddiruppuPadeniyaPadikaramaduwaPadiyapelellaPadiyathalawaPadukkaPadukumburaPahala GiribawaPahala PuliyankulamaPahala TammannewaPahala WeliyawaPahalakumburaPahamunegamaPaiyagala NorthPaiyagala SouthPalagalaPalaicholaiPalaikkudaPalaimoddaiPalaiyavadiPalaliPalamaduPalamattalanPalameenmaduPalampiddiPalampsPalamunaiPalapatwelaPalapotaPalatoppuPalattadichchenaiPalatupanaPalaturuellaPalatuwaPalavi (Poonakary)Palavi (Puttalam)PalawelaPaldeniyaPalindanuwaraPallaiPallamaPallamaduPallataraPallavarayankadduPallebahirawaPallebeddaPallegama (Dambulla)Pallegama (Laggala-Pallegama)PallekandaPallekiruwaPallemallehewaPallepolaPallewattaPallewela (Embilipitiya)Pallewela (Kandaketiya)Pallewela (Mirigama)PallikundawayalPalliyaddaPalliyagodellaPallugaturaiPalugamaPalugassegamaPalugaswewa (Anamaduwa)Palugaswewa (Palugaswewa)PalugollaPalugollewaPalukadawalaPalukamamPalukandewaPaluketuwewaPalwatavankerniPampaimaduPamunugamaPanaduraPanagoda (Homagama)Panagoda (Passara)PanamaPanamurePananePanangalaPanankaduPanankamamPanapitiya (Kahawaththa)Panapitiya (Kaluthara)PanchenaiPandattarippuPandiggamaPandisurichchanPanduwas NuwaraPangaragammanaPanguraPanguranaPangurugaswewaPanichchankeniPanikkaniraviPanikkankulamPanikkapettankulamPanilkandaPankudavellPankulamPankunaveliPannaiyedduvanPannala (Pannala)Pannala (Walapane)PannampitiyaPannegamuwaPannila (Kahawaththa)Pannila (Walallawita)PansalagodaPanveliPanwilaPanwilatennaPappamoddaiParagahakeleParagalaParagastotaParaigamaParaiyanalankulamParakaduwaParakramapuraParakumpuraParamakandaParana HammillewaParanagamaParangiyawadiyaParantanParappukalParasangahawewaParasankulamParawahagamaPasbage KoralePasgodaPassaraPassikudahPasyalaPatampitiyaPatchenaiPathadumbaraPathahewahetaPattewaPattigodaPattipolaPattiyagamaPattiyapolaPavakkodichchenaiPavatkayikkulamPayaindikulamaPayirimaduwaPaymaduwaPeipolaPelawatta (Kalawana)Pelawatta (Walallawita)PelbendiyawaPelmadullaPelwattaPelweheraPeparaputtiPeradeniyaPeralandaPeriyakadduPeriyakkulam (Medawachchiya)PeriyakulamaPeriyakunchukkulam (Madhu)Periyamadu (Manthai West)Periyamadu (Vavuniya North)PeriyamaduwaPeriyamurippuPeriyanilavanaiPeriyanthuraiPeriyaparantanPeriyaporativuPeriyathampanaiPerukkuwattanPesalaiPetiyannekadaPettewaPewuwewaPihimbiyagollewaPilihudugollaPiliyandalaPimbura (Agalawatta)Pimbura (Ayagama)PindeniyaPingomuwaPinnagollaPinnawala (Hanwella)Pinnawala (Imbulpe)PinogamaPiramanalanPirappammaduvaPirappuvedduvanPitabeddaraPitakumburaPitamaruwaPitawelaPitiduwaPitigalaPituwalaPiyadigamaPoddalaPodinaddamporePohoregedaraPoint PedroPokkarvanniPokunuwitaPolattawaPolgahagamaPolgahagangodaPolgahawelaPolgampolaPolgasowitaPolgaswattaPolkotan ArawaPollebeddaPolmotePolonnaruwaPolpithigama (Polpithigama)PolpogodaPolwattegamaPomparippuPoojapitiyaPoonakaryPoonerynPorativu PattuPorawagamaPotanaPotanegamaPotankaduPottuvilPotuheraPotuliyaddaPotupitiyaPotuwewaPotuwilaPubbarawelaPubberapotaPubbiliyaPubbowaPuddakkarachaiPudukudiyirippuPudurPugallegamaPugodaPuhambugodaPukakgahaPuliadimoddipulavuPuliyampokkanaiPuliyankulam (Anamaduwa)Puliyankulam (Galenbidunuwawe)Puliyankulam (Horowpothana)Puliyankulam (Vanathavilluwa)Puliyankulam (Vavuniya North)PulladiputtiPullaveliPullumalaiPulmoddaiPuloliPulukunavaPumaduwaPumunaiPunaidiPunanaiPundaluoyaPunewaPunnaikudaPunugalaPupuressaPuralewelaPuranwelaPussella (Ambanganga Koralaya)Pussella (Kuruwita)PussellawaPuthukkudiyiruppuPuttalamPuttukaduPutturPutukkulam (Oddusuddan)Putukkulam (Vavuniya)PutumattalanPutupagalaPuturPutuvilankulamPuvarasankandalPuvarasankulamPuwakgahakotuwaPuwakgahawadiyaPuwakgahawalaPuwakpitiya (Hanwella)Puwakpitiya (Laggala-Pallegama)PuwarasankulamaPyrandawaRadagama (Anamaduwa)Radagama (Thambuttegama)RadagodaRadaliyaddaRadawanaRaddellaRadeniyaraRadunnewelaRagalaRagamaRajakadaluwaRajanganayaRajawakaRajgamaRakwanaRambakepuwewaRambawewaRambeRambewa ( Palugaswewa)Rambewa (Rambewa)RambodaRambodagallaRambukaRambukewelaRambukkanaRambukpitiyaRambukpotaRanakeliyaRanamureRanapanadeniyaRanawaRanawaranawewaRanchamadamaRandeniyaRangalaRangedaraRannaRanorewaRanwalaRasnayakapuraRassagalaRathmalanaRathnapuraRatmalagaha_ela (Dambulla)Ratmalagaha_ela (Nuwaragam Palatha Central)Ratmalagahawewa (Kahatagasdigiliya)Ratmalagahawewa (Rambewa)RatmalanaRatmale (Devinuwara)Ratmale (Hingurakgoda)Ratmale (Horowpothana)Ratmale (Mahawa)Ratmale (Nachchadoowa)RatmalweheraRatnapuraRattotaRekawaRelapanawa (Horowpothana)Relapanawa (Kebithigollewa)Relapanawa (Medawachchiya)RelapanawewaRerupitiyaRevulvalaRideegamaRideemaliyaddaRidiellaRidigamaRidiyagamaRikillagaskadaRilaullaRittawelaRotawewa (Hingurakgoda)Rotawewa (Rambewa)RotumbaRozellaRukamputurRuwanwellaSagamamSaintamaruthu (Kalmunai)Sainthamarathu (Sainthamarathu)SamanthuraiSamithoddamunaiSampaltivuSampurSandichenaSandilipaySangilikanadarawaSarasalaiSaravanaiSeeduwaSeenigaslandaSellankandalSembukuliyaSempaduSenarathgamaSengamuwaSengapadaiSeranegamaSerankadaSeruwawilaSesseruwaSewanagalaSigiriyaSilavatturalSinhalagodaSinharagamaSinnamuhattuvaramSinnappullumalaiSinnapputukulamSinnathampanaiSinuggalaSippukulamSirambiyadiSiripuraSita EliyaSitawakaSittandiSittaramaSittaraveliSiwalakulamaSiyambalagaswewa (Galewela)Siyambalagaswewa (Palugaswewa)Siyambalagaswewa (Thirappane)SiyambalagodaSiyambalaguneSiyambalanduwaSiyambalangamuwaSiyambalewa (Galnewa)Siyambalewa (Horowpothana)Siyambalewa (Thirappane)Slave IslandSodayankulamSohonkalmaSomapuraSomativadiSonakasalampaikkulamSooriyawewaSoranathotaSoranpattuSorikalmunaiSrawastipuraSri Jayawardanapura KotteSri JayawardanepuraStripuregamaSuduventapulavuSultanagadaSungawilaSunkankuli (Eachchilampattai)Sunkankuli (Muttur)Suriya AraSuriyakandaSuriyawewaSuruveliSuruvilTabbowaTaddamalaiTadduvankoddaiTalabowattaTalagalaTalagodaTalahenaTalaimannarTalaimannar PeriTalaivilluTalakiriyagamaTalakolawelaTalakolawewa (Buttala)Talakolawewa (Kahatagasdigiliya)Talakolawewa (Medirigiriya)TalangallaTalangamaTalapitiyaTalatu OyaTalawa (Angunukolapelessa)Talawa (Polpithigama)Talawa (Thalawa)TalawakeleTalawattegedaraTalawegamaTalayagamaTaldenaTalgahadiganeTalgahawewaTalgamaTalgampolaTalgaspeTalgaswelaTalgaswewa (Anamaduwa)Talgaswewa (Nochchiyagama)TalgodapitiyaTalkotaTalladiTalpawilaTalpeTalunnaTalvupaduTamaraivilluTambalaTambalagollewaTambareTambiyawaTambuttaTambuttegamaTammannawetiyaTammannekulamaTammannewa (Kebithigollewa)Tammannewa (Mihintale)TammenweTampaddaiTampalakamamTanamalwilaTandikkulam (Musalai)Tandikkulam (Vavuniya)TanduvanTanebaddegamaTangalleTanjamaTanjanagaramTanmakkeniTannamunaiTanniyuttuTantirimalaiTarakkunduTattewaTavasiyakulamTawalamaTayliankudiyiruppuTebuwanaTeligamaTelijjawilaTelikadaTellippalaiTellula (Hambantota)Tellula (Wellawaya)TelwatteTembichchiyaTenagamaTennaheraTennamaravadiTenniyankulamTennugeTentukkiTeppanawaTeripehaTerumurikandiTetapolaiTettativuThachchanthoppuThalankudahThalawaThamankaduwaThambuttegamaThampalakamamThanamalwilaThanddankulamThankodaiThawalamaTheethakaraiThekampuddiThenketiyaThihagodaThimbirigasyayaThirappaneThirukesvaramThirukethiswaramThirukkovilThottamaThumpaneTibbotuwawaTihagodaTihariyaTikaliTikkanpotanaTillaiyadiTimbiriyawaTimbolketiyaTimirigahamankadaTinipitigamaTinneriveliTinniyawalaTippapottaTirappane (Gomarankadawela)Tirappane (Thirappane)TiriyaiTirukkovilTirukkulamTiruwanaketiyaTismalpolaTissamaharamaTiththawelkeulaTittagonewaTittawelgollaToddaveliToduwawaTondaimanarTonigalaToppurTorakotuwaTorawelaTown &amp; GravetsTrikonamaduTudarikkulamTudugallaTulawelliyaTumbatennaTumbullegamaTummodaraTumpalaiTumpalancholaiTumpankeniTunkameTunnalaiTunukkaiTussamaharamaTuttiripitiya (Ehetuwewa)Tuttiripitiya (Nivithigala)Tuttiripitiya (Udubaddawa)TuvaraneriUdacambanaUdadumbaraUdagaladebokkaUdagama (Buttala)Udagama (Lunugala)Udagama (Mawathagama)UdagammeddaUdahentennaUdaiyadiUdaiyarthuraiUdakandegamaUdamalalaUdamattalaUdamullaUdapalathaUdapollaUdappuwaUdapussellawaUdatuttiripitiyaUdawalakandaUdawelgodaUdayalaUdayarsamalankulamUdispattuUdubaddawaUdugama (Nagoda)Udugama (Pannala)Udugama (Walallawita)UdugampolaUdumbugalaUdunuwaraudupilaUdutturaiUduvilUduwaraUduwelaUduwelwalaUduweriyaUduwilaUggalkaltotaUhanaUhanowitaUhumiyaUkuwelaUlagallaUlapaneUllapolaUlpatgamaUlpotaUlpotegamaUlpothawewaUlukkulamUlukkulamaUlullaUnawatunaUnchalkaddiUndugodaUndurawaUnichchaiUpcotUpparuUppukaliUppuralUppuveliUragasmanhandiyaUralaUralkulattuvadiUraniUraniyaUrapola (Attanagalla)Urapola (Kamburupitiya)UriyanUrubokkaUrukamamUrumpiraiUrupitiyaUruwalaUrvanikanpattuUsangodaUssapitiyaUswetakeiyawaUswewa (Angunukolapelessa)Uswewa (Giribawa)UthuvayankulamUttimaduwaUttukkulamUva ParanagamaUyangodaUyilankulamVaddakkachchiVaddakkandalVaddukkoddaiVadduvakalluVaiaichchenaiVakaneriVakaraiValaichendiValappaduValayanmadamVallivappalaiValpotuwewaValvedditturaiVanathavilluwaVankalaiVannankulam (Madhu)Vannankulam (Maruthnkerny)VannatitalVannativilluVantarumulaiVaraniVarikutturuwaVaripattanchenaiVasavilanVattappalaiVavuniyaVavuniya NorthVavuniya SouthVayiriuttuVedativuVeddukkadduVedivaittakalluVeeramalaiVeerramunaiVeherabendigalaVelanaiVellai (Delft)Vellai (Seruvila)VellaiyadimaduVellamullivaikalVellankulam (Manthai West)Vellankulam (Vavuniya)VellaveliVengalacheddiculamVeppankulamVeranativuVeravilVerugalVettilaikkeniVettilaipoddamaduVeyangodaVidatalpalaiVidattaltivuViharahenaViharehinneVilattikkulamWadakadaWadduwaWadigewewaWadinagalaWadurawaWagaWagollakadaWahaganapuwewaWahakotteWaharakaWaiganeliyeWakwellaWalagammullaWalagedara (Mathugama)Walagedara (Udunuwara)WalagodaWalahapitiyaWalakandaWalakumburaWalaliyaWalallawitaWalapaneWalasgalaWalasmullaWalebodaWalpitaWalpola (Gampaha)Walpola (Polgahawela)Walpola (Yakkalamulla)WanawasalaWandurambaWanduruppeWannappuwaWaradeniyawaWarakagoda (Kotapola)Warakagoda (Madurawala)WarakapolaWaralandaWarallaWarapitiya (Mahaoya)Warapitiya (Walasmulla)WarawewaWariyapolaWarralandeWaskaduwaWatagodaWatapotaWatawalaWathupitiwalaWattaWattala (Kelaniya)Wattala (Wattala)WattappolaWattaramaWattegama (Pathadumbara)Wattegama (Siyambalanduwa)Wattegedara (Kuliyapitiya East)Wattegedara (Polgahawela)WattegepelessaWattekeleWattewewaWatugalaWatuheraWaturaWaturugamaWaywattaWedagamaWeddagalaWedeniyaWedikumburaWeeraketiyaWeerambugedaraWegamaWegollemadaWeheraWeheragodaWekadaWekeWelagedaraWelandapitiyaWelanpelaWelanwitaWelenewattaWelewaWelgahawadiyaWeligahakandiyaWeligama (Weligama)Weligama (Welipitiya)WeligattaWeligepolaWelihinnaWelikandaWelimadaWelimapotanaWelipennaWelipitiya (Welipitiya)Welipitiya(Katuwana)Welivitiya (Divithura)WeliwaranagollaWeliweriyaWeliwewaWeliwitaWeliyawa (Ehetuwewa)Weliyawa (Galnewa)WellarawaWellawaWellawattaWellawayaWelpallaWennappuwaWeragala (Beruwala)Weragala (Palugaswewa)Weragama (Rattota)Weragama (Vavuniya South)WeragantotaWeragodaWeralugamaWerapitiyaWerapokunaWerellagamaWessigewelaWetakeyapotaWetambodaWetiyaWeudaWidiyawattaWigamuwaWikiliyaWilattawaWilegamaWilewewaWilgamuwaWillaWillwattaWilpitaWiraketiyaWirapanaWirapokuna (Bingiriya)Wirapokuna (Giribawa)WirawewaWirawilaWitaranadeniyaYagodaYahalaYakallaYakawewaYakkalaYakkalamullaYakkuragalaYakkureYalaYalakumburaYalegamaYalkumburaYalogamaYalwelaYantampolagamaYapahuwaYatagampitiyaYatawattaYaththalgodaYatinuwaraYatiwalaYatiyanaYatiyanthotaYodagannawaYodakandiyaYogamaYudaganawaKatuwaawalaRajagiriyaKiribathgodaAthurugiriyaBaththaramullaPannipitiyaKadaanaWaththalaKatharagamaMeepeBokundaraAluthkadeEhaliyagodaAththidiyaAnuradhapuraKatubeddaMalabeDelkadaThalawathugodaMattegodaWewaladeniyaGothatuwaWellampitiyaKohuwalaRaththanapitiya (Moneragala)Raththanapitiya (Kesbewa)PepiliyanaMount LaviniaMaarawilaWattegedara (Maharagama)RabukkanaWelisaraNawalaPilimathalawaAluthgamaKalubowilaMirihanaKirulapanaMaradagahamullaKirillawalaBorellaHokandaraDematagodaAtharagamaKotikaawattaKotahenaOrugodawattaGonawilaMoragahahenaKiribathkuburaKiriwaththuduwaRukmalgamaPitakotteTrincomaleeMulleriyawaAbathennaRanalaSiddamullaThalgahapitiyaEthulkotteEwariwattaKeragalaPallawaRaddolugamaNikadalupothaRajawellaPagoda (Rathnapura)Pagoda (Sri Jayawardanapura Kotte)Bowaththa (Balangoda)Bowaththa (Pannala)Bowaththa (Bingiriya)Bowaththa (Ukuwela)Werahera (Kesbewa)Werahera (Godakawela)Werahera (Pannala)WatapuluwaMadiwelaMaradana (Colombo)Maradana (Beruwala)Maligawatta (Mahawewa)Maligawatta (Colombo)SapugaskandaUdahamulla (Panadura)Udahamulla (Maharagama)BolgodaThotalaga (Haputhale)Thotalaga (Colombo)Havelock TownThudellaPolgollaPeliyagodaGrandpassGangodawilaGunnepanaModaraMattakkuliyaHimbutanaPitipanaAmar StreetArawwalaKatugampalaBopitiyaThorana HandiyaThalwatta (Kelaniya)Thalwatta (Katuwana)Thalwatta (Gangawata Korale)AmpitiyaButhgamuwaPayagalaBakamunaWeerawila Udawalawe Kilinochchi Akarawita (Hanwella) Akarawita (Gampaha) GonamullaVilachchiya Arugam BayKottaramullaNayinamadama Galwana SiyambalapeBellanaMahabellanaKarapitiyaKohilawattaBatapotha (Minuwangoda)Batapotha (Kaduwela)Mabima (Biyagama)Mabima (Gampaha)PanchikawattaOruwalaWaikkalAlahitiyawaBatticaloaHeiyanthuduwaPallekele (Madampe)Pallekele (Kundasale)ValaichchenaiAll islandHanthana 
	
	
	
	
     var agentCode = 'DEFZZZ'
    
	













div.hidden{display:none;}
#LocSwitch:hover{border-bottom:1px solid black; padding-bottom:1px;}



 Show Locations(0)  





$(document).ready(function(){
	$(&quot;#hidden-towns&quot;).val(&quot;&quot;);// some browsers are smart enough to keep around input field data on page refresh. note: can be used to populate the list again. No time now. handle in a later issue
	var townList = new Array(); 
	
	/**-- add town codes to the townList on edit, reopen --**/
	if(townList.length &lt; 1){
		$('.delete-location').each(function(i,v){
			
			var code = $(this).attr('data-town');
			townList.push(code);
		
		});
	}
	
	/** set the hidden fields with the location codes**/
	if(townList.length > 0){
		for(each in townList)
			  $('#hidden-towns').val($('#hidden-towns').val()+townList[each]+&quot;_&quot;); // set codes to hidden field for posting 		
	}

	
	/**open locations popup**/
	$( &quot;.showlocation&quot; ).click(function() {
	    $( &quot;.popTbl&quot; ).dialog( &quot;open&quot; );
	});


	/**-- Add selected town to list --**/
	$('#add-location').click(function(){
		  
		 var tc = $('#towns').find(&quot;:selected&quot;).val();
		 var town = $('#towns').find(&quot;:selected&quot;).text();
		 var country = $('#countries').find(&quot;:selected&quot;).text();
		 
		 country = (tc == &quot;-2&quot;)?'':country+&quot;, &quot;;
		 $('#LocInformation').html(&quot;&quot;);
		 
		 /**-- ensures that the user selects a town --**/
		 if(town == null || town == &quot;&quot; || $('#towns').siblings(&quot;.custom-combobox&quot;).find(&quot;input&quot;).val() == &quot;&quot;){
			 $('#LocMsg').html('Select a town');
			 return false;
		 }
		 
		 if($.inArray(tc, townList) == -1){// -1 indicates that the town is not in the townList
		
		  townList.push(tc);
		  $('#hidden-towns').val($('#hidden-towns').val()+tc+&quot;_&quot;); // set codes to hidden field for posting 
		 
		  var row = &quot;&lt;tr class = \&quot;location-row\&quot;> &lt;td class = \&quot;location-row-num\&quot;>&quot;+townList.length+&quot;&lt;/td> &lt;td class='townColm' align='center'>&quot;+country+&quot;&quot;+town+&quot;&lt;/td> &lt;td align='center'>&lt;a href = \&quot;#\&quot; class = \&quot;remove-location\&quot; data-town=\&quot;&quot;+tc+&quot;\&quot; >&lt;img title='Remove Location' src='/images/remove_location.png'>&lt;/a> &lt;/td>&lt;/tr>&quot;;		  
		  $('#location-tbody').append(row);
			  
		  if($('.showLocation').hasClass('hide') == false)
			  $('.showLocation').addClass(&quot;show&quot;).removeClass(&quot;hide&quot;);
		 //clear the message and the variables.	
				$(&quot;body&quot;).find('.custom-combobox').css(&quot;border-left&quot;,&quot;none&quot;); 
				$(&quot;body&quot;).find('.custom-combobox').css(&quot;border-top&quot;,&quot;none&quot;); 
				$(&quot;body&quot;).find('.custom-combobox').css(&quot;border-bottom&quot;,&quot;none&quot;); 
				$(&quot;body&quot;).find('.custom-combobox-toggle').css(&quot;border-left&quot;,&quot;1px solid #D3D3D3&quot;); 
				$(&quot;body&quot;).find(&quot;#errTown&quot;).html(&quot;&quot;);
		 $('#LocMsg').html('');	//clear the message and the variables.	
		 $('#towns').siblings(&quot;.custom-combobox&quot;).find(&quot;input&quot;).val(&quot;&quot;);
		 $('#LocInformation').html(&quot;location selected: &quot;+country+&quot; &quot;+town+&quot;&quot;);
		 $('#ListLeng').html(&quot;(&quot;+townList.length+&quot;)&quot;);
		 tc = null; town = null; country = null;	
		 
		 }else
	 		$('#LocMsg').html('Already Selected');
		 
		  
		//$('.showlocation').trigger('click'); //open locations popup  
		$('#LocSwitch').removeClass(&quot;hideLocation&quot;).addClass(&quot;showLocation&quot;);	
	});	
	
	/**-- remove item from list. --**/
	$(document).on('click','.remove-location', function(){
	   
		var town = $(this).attr('data-town');
		$(this).closest('tr').remove();
		/** remove town from array and renumber list**/
		townList = removeTownFromList(town, townList);
	    $('#ListLeng').html(&quot;(&quot;+townList.length+&quot;)&quot;);
		var towRem=$(this).parent().parent().find('.townColm').text();
		 $('#LocInformation').html(&quot;Sucessfully Removed : &quot;+towRem+&quot;&quot;);
		
	});


	/*-- Delete item from list. This effects the DB --*/
	$('.del-img').click(function(){
		
		var elem = $(this).parent();
		var locale = $(this).parent().attr('data-locale');
		var town = $(this).parent().attr('data-town');
		var townName = $(this).parent().attr('data-townName');
		var job = $(&quot;#jobCode&quot;).val();
		console.log(&quot;town list:  &quot;+townList);
		console.log(&quot;town code: delete:  &quot;+town);
		
		$.ajax({
			type: &quot;POST&quot;,
			dataType: &quot;json&quot;,
			url: &quot;/employer/JobAdvertismentServlet?EAC=&quot;+$('#djl').val()+&quot;&quot;,
			data: {locale:locale, job:job},
			success: function(response){
				console.log(&quot;delete: response: &quot;+response);
				if(response.success == true){
					
					/** remove table row**/
					elem.parent().remove();
					/** remove town from array and renumber list**/
					townList = removeTownFromList(town, townList);
					var delTown=elem.parent().find('.delTownCol').text();
				    
					console.log(&quot;town list:  &quot;+townList);
					$('#ListLeng').html(&quot;(&quot;+townList.length+&quot;)&quot;);
					$('#LocInformation').html(&quot;Delete successful. Location deleted: &quot;+delTown);
				}else{
					$('#LocMsg').html('The Delete failed. Please try again');
				}
					
			}
		});
	});

	/**removes the 'display: none' set on the locations table. it was set through css**/
	$('div .popTbl').removeClass(&quot;hidden&quot;);



});

/**private function: remove town from list and renumber the table**/
function removeTownFromList(town, townList){
	
	/** remove town code from the array 'townList' '**/
	if($.inArray(town, townList) != -1)
		townList = $.grep(townList, function(value){ return value != town;});
	
	/**renumber the table rows**/
    $('.location-row-num').each(function(i,v){
    	$(this).text(i+1);
    });
	
    $('#hidden-towns').val(&quot;&quot;);
	for(each in townList)
	  $('#hidden-towns').val($('#hidden-towns').val()+townList[each]+&quot;_&quot;); // set codes to hidden field for posting 
	  
	 if(townList.length == 0){
		 $( &quot;.popTbl&quot; ).dialog( &quot;close&quot; );
		 $('#LocSwitch').removeClass(&quot;showLocation&quot;).addClass(&quot;hideLocation&quot;);	
	 }
	return townList;
	
}
 
 
 

	 
	
	
	</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmJobSpec&quot;)/table[1]/tbody[1]/tr[9]/td[2]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmJobSpec']/table/tbody/tr[9]/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
